### ISSUE TITLE
Forge.ProjectSystem not resolving references with `\` on *nix

### ISSUE THREAD

**Issue by tpetricek** [fsharp-editing/Forge#168]
I'm using [Fable 0.7.0](https://github.com/fable-compiler/Fable/tree/0.7.0) which relies on Forge to parse project files. Typically, the references in project files are written using Windows-style relative references and I had a couple of places with:

```
<HintPath>..\..\node_modules\fable-core\Fable.Core.dll</HintPath>
```

This works on Windows but not on Linux (here is a [failing Travis build](https://travis-ci.org/the-gamma/thegamma-script/builds/171874285)). Switching to nix relative paths [like this](https://github.com/the-gamma/thegamma-script/commit/407d5aefa9f3a2f81feb9492599ce69c659d4a90) solves the problem - they work on Windows too.

I think it would be nice if Forge normalized the paths so that the user of the API does not have to worry about this.

/cc @alfonsogarciacaro @ncave

**Comment by alfonsogarciacaro** [comment]
If Forge's purpose it's just to parse the .fsproj file and not interpret it anyway, I'm not sure normalization should be done here. Maybe we could do the it in Fable but, does the issue affect only references? For source files it can be tricky because latest Fable creates a file map when compiling dlls to map the file names of the types in the dll with the generated JS files. If source file paths read by Forge get normalized, they won't match the metadata in the assembly (though this could also by fixed by making Fable normalize file names read from an assembly.

**Comment by Krzysztof-Cieslak** [comment]
TBH, I don't think such normalisation should be part of `Forge`. We manipulate on raw data, don't try to interpret it. 

Closing it for now, but feel free to continue discussion :)
